# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(271, 400)
        MainWindow.setMinimumSize(QtCore.QSize(271, 400))
        MainWindow.setMaximumSize(QtCore.QSize(271, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.volume_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.volume_frame.setGeometry(QtCore.QRect(20, 40, 235, 111))
        self.volume_frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.volume_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.volume_frame.setObjectName("volume_frame")
        self.button_volume_up = QtWidgets.QPushButton(parent=self.volume_frame)
        self.button_volume_up.setGeometry(QtCore.QRect(0, 30, 113, 32))
        self.button_volume_up.setObjectName("button_volume_up")
        self.button_volume_down = QtWidgets.QPushButton(parent=self.volume_frame)
        self.button_volume_down.setGeometry(QtCore.QRect(120, 30, 113, 32))
        self.button_volume_down.setObjectName("button_volume_down")
        self.button_mute = QtWidgets.QPushButton(parent=self.volume_frame)
        self.button_mute.setGeometry(QtCore.QRect(60, 70, 113, 32))
        self.button_mute.setObjectName("button_mute")
        self.label_volume = QtWidgets.QLabel(parent=self.volume_frame)
        self.label_volume.setGeometry(QtCore.QRect(30, 10, 51, 16))
        self.label_volume.setObjectName("label_volume")
        self.progress_bar_volume = QtWidgets.QProgressBar(parent=self.volume_frame)
        self.progress_bar_volume.setGeometry(QtCore.QRect(100, 10, 118, 16))
        self.progress_bar_volume.setMaximum(10)
        self.progress_bar_volume.setProperty("value", 0)
        self.progress_bar_volume.setObjectName("progress_bar_volume")
        self.channel_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.channel_frame.setGeometry(QtCore.QRect(20, 160, 235, 201))
        self.channel_frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.channel_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.channel_frame.setObjectName("channel_frame")
        self.button_channel_up = QtWidgets.QPushButton(parent=self.channel_frame)
        self.button_channel_up.setGeometry(QtCore.QRect(0, 170, 113, 32))
        self.button_channel_up.setObjectName("button_channel_up")
        self.button_channel_down = QtWidgets.QPushButton(parent=self.channel_frame)
        self.button_channel_down.setGeometry(QtCore.QRect(120, 170, 113, 32))
        self.button_channel_down.setObjectName("button_channel_down")
        self.graphics_view_channel = QtWidgets.QGraphicsView(parent=self.channel_frame)
        self.graphics_view_channel.setGeometry(QtCore.QRect(0, 0, 231, 171))
        self.graphics_view_channel.setObjectName("graphics_view_channel")
        self.button_power = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_power.setGeometry(QtCore.QRect(20, 10, 113, 32))
        self.button_power.setObjectName("button_power")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 271, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Remote"))
        self.button_volume_up.setText(_translate("MainWindow", "VOL +"))
        self.button_volume_down.setText(_translate("MainWindow", "VOL -"))
        self.button_mute.setText(_translate("MainWindow", "MUTE"))
        self.label_volume.setText(_translate("MainWindow", "Volume"))
        self.button_channel_up.setText(_translate("MainWindow", "CH +"))
        self.button_channel_down.setText(_translate("MainWindow", "CH -"))
        self.button_power.setText(_translate("MainWindow", "POWER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
